### ISSUE TITLE
Data Question

### ISSUE THREAD

**Issue by angle011** [mpapadomanolaki/UNetLSTM#6]
Hello,
Thanks for your work!
I want to reproduce the result about your model.However the OSCD dataset only have two images not five ,Can you share the mid time dataset?(Or give some tips about finding mid-time images)

**Comment by mpapadomanolaki** [comment]
Hello,

Sorry for the late reply.
Can you send me your email to mar.papadomanolaki@gmail.com?
So that I can attach the dataset.
Thanks!

**Comment by IwantNewway** [comment]
> Hello, Thanks for your work! I want to reproduce the result about your model.However the OSCD dataset only have two images not five ,Can you share the mid time dataset?(Or give some tips about finding mid-time images)

请问可以分享一下数据集么？谷歌邮箱好像发不过去
